INSERT INTO cars (manufacturer, model, cc, doors, available, year, release_date) VALUES ('Honda','Jazz',1.2,3, true, 2008, '2003-12-12');
INSERT INTO cars (manufacturer, model, cc, doors, available, year, release_date) VALUES ('Rolls Royce','Silver Ghost',19.5,6, true, 2010, '2003-10-12');
INSERT INTO cars (manufacturer, model, cc, doors, available, year, release_date) VALUES ('Ferrari','Testarossa',9.2,3, true, 2012, '2000-12-12');
INSERT INTO cars (manufacturer, model, cc, doors, available, year, release_date) VALUES ('Tesla','Electra',1.5,3, true, 2014, '2000-12-12');
INSERT INTO cars (manufacturer, model, cc, doors, available, year, release_date) VALUES ('Honda','Civic',1.2,5, true, 2014, '2003-12-12');
INSERT INTO app_users (username, email, password) VALUES ('rnoguera','rnogueradrum@gmail.com', '$2a$10$mVbq2kUyQtadt0mlakfzfuP2molhy.r4VP3S1KCrTRFQmo1bhtWJm');
INSERT INTO app_users (username, email, password) VALUES ('Prince', 'prince@gmail.com','$2a$10$NOCpEHp5/qYoJmFQSvAr7e0Qz8eF5BKqQLA6X5BynGDFBIhF5iKO2');
INSERT INTO app_users (username, email, password) VALUES ('Stewart Copeland', 'copelan@gmail.com', '$2a$10$yc/EmUoC8rSgpIUAHP/4tOrSBun.Y6oiRd8qRiFR5ULJ4cqr4h82i');
INSERT INTO app_users (username, email, password) VALUES ('Roger Taylor', 'rogertaylor@gmail.com', '$2a$10$IQZJH2vmtXMOVpfmkygRdus9WAtwLeWz2IggDSWMaU9e9R0HZS6v2');
INSERT INTO app_users (username, email, password) VALUES ('Buddy Rich', 'buddyrich@gmail.com', '$2a$10$Ju/EOQEHEWDAu1I7jSbliu9SeAjwGiGhAmBoLJ6HtAGBGZU2te2wO');
insert into app_users(username, email, password) values ('alan', 'alan@alan', '$2a$10$qINz45KQzkLHtzOovvgjn.y1SKh8zfR5Meyh61FHz3bvSlO4uez.O');